version: '2'
services:
  web:
    image: odoo:14.0
    container_name: odoo_14
    user: root
    depends_on:
      - db
    ports:
      - 9000:8069
      - 9001:8072 # for live chat
    volumes:
        - ./data/odoo:/var/lib/odoo
        - ./config:/etc/odoo
        - ./addons:/mnt/extra
    environment:
      - HOST=db
      - USER=odoo14
      - PASSWORD=odoo14
    restart: always
  db:
    image: postgres:12
    container_name: postgres_12
    user: root
    environment:
      - POSTGRES_PASSWORD=odoo14
      - POSTGRES_USER=odoo14
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
