
version: '1.0'
services:
  web:
    image: odoo:15.0
    container_name: odoo_15
    depends_on:
      - db
	ports:
	  - "90015:8069"
	  - "80015:8072" # For live chat
	volumes:
      - ./odoo:/var/lib/odoo
      - ./etc:/etc/odoo
      - ./addons:/mnt/extra
    environment:
      - HOST=db
      - USER=odoo15
      - PASSWORD=odoo15@strong_password
  db:
    image: postgres:12
    container_name: postgres_12
    ports:  
      -5432:5432
    volumes:  
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=odoo15@strong_password
      - POSTGRES_USER=odoo15
      - POSTGRES_DB=postgres 
